In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("DataCoSupplyChainDataset.csv",encoding = "latin1")
data.head(10)

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class
5,TRANSFER,6,4,18.580000,294.980011,Shipping canceled,0,73,Sporting Goods,Tonawanda,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/19/2018 11:03,Standard Class
6,DEBIT,2,1,95.180000,288.420013,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:42,First Class
7,TRANSFER,2,1,68.430000,285.140015,Late delivery,1,73,Sporting Goods,Miami,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 10:21,First Class
8,CASH,3,2,133.720001,278.589996,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 10:00,Second Class
9,CASH,2,1,132.149994,275.309998,Late delivery,1,73,Sporting Goods,San Ramon,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 9:39,First Class

In [3]:
data.shape

(180519, 53)

In [4]:
data.info

<bound method DataFrame.info of             Type  Days for shipping (real)  Days for shipment (scheduled)  \
0          DEBIT                         3                              4
1       TRANSFER                         5                              4
2           CASH                         4                              4
3          DEBIT                         3                              4
4        PAYMENT                         2                              4
...          ...                       ...                            ...
180514      CASH                         4                              4
180515     DEBIT                         3                              2
180516  TRANSFER                         5                              4
180517   PAYMENT                         3                              4
180518   PAYMENT                         4                              4

        Benefit per order  Sales per customer   Delivery Status  \
0               91.250000          314.640015  Advance shipping
1             -249.089996          311.359985     Late delivery
2             -247.779999          309.720001  Shipping on time
3               22.860001          304.809998  Advance shipping
4              134.210007          298.250000  Advance shipping
...                   ...                 ...               ...
180514          40.000000          399.980011  Shipping on time
180515        -613.770019          395.980011     Late delivery
180516         141.110001          391.980011     Late delivery
180517         186.229996          387.980011  Advance shipping
180518         168.949997          383.980011  Shipping on time

        Late_delivery_risk  Category Id   Category Name Customer City  ...  \
0                        0           73  Sporting Goods        Caguas  ...
1                        1           73  Sporting Goods        Caguas  ...
2                        0           73  Sporting Goods      San Jose  ...
3                        0           73  Sporting Goods   Los Angeles  ...
4                        0           73  Sporting Goods        Caguas  ...
...                    ...          ...             ...           ...  ...
180514                   0           45         Fishing      Brooklyn  ...
180515                   1           45         Fishing   Bakersfield  ...
180516                   1           45         Fishing       Bristol  ...
180517                   0           45         Fishing        Caguas  ...
180518                   0           45         Fishing        Caguas  ...

       Order Zipcode Product Card Id Product Category Id  Product Description  \
0                NaN            1360                  73                  NaN
1                NaN            1360                  73                  NaN
2                NaN            1360                  73                  NaN
3                NaN            1360                  73                  NaN
4                NaN            1360                  73                  NaN
...              ...             ...                 ...                  ...
180514           NaN            1004                  45                  NaN
180515           NaN            1004                  45                  NaN
180516           NaN            1004                  45                  NaN
180517           NaN            1004                  45                  NaN
180518           NaN            1004                  45                  NaN

                                            Product Image  \
0            http://images.acmesports.sports/Smart+watch
1            http://images.acmesports.sports/Smart+watch
2            http://images.acmesports.sports/Smart+watch
3            http://images.acmesports.sports/Smart+watch
4            http://images.acmesports.sports/Smart+watch
...                                                   ...
180514  http://images.acmesports.sports/Field+%26+Stre...
180515  http://images.acmesports.sports/Field+%26+Stre...
180516  http://images.acmesports.sports/Field+%26+Stre...
180517  http://images.acmesports.sports/Field+%26+Stre...
180518  http://images.acmesports.sports/Field+%26+Stre...

                                     Product Name Product Price  \
0                                    Smart watch     327.750000
1                                    Smart watch     327.750000
2                                    Smart watch     327.750000
3                                    Smart watch     327.750000
4                                    Smart watch     327.750000
...                                           ...           ...
180514  Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180515  Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180516  Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180517  Field & Stream Sportsman 16 Gun Fire Safe    399.980011
180518  Field & Stream Sportsman 16 Gun Fire Safe    399.980011

       Product Status shipping date (DateOrders)   Shipping Mode
0                   0             2/3/2018 22:56  Standard Class
1                   0            1/18/2018 12:27  Standard Class
2                   0            1/17/2018 12:06  Standard Class
3                   0            1/16/2018 11:45  Standard Class
4                   0            1/15/2018 11:24  Standard Class
...               ...                        ...             ...
180514              0             1/20/2016 3:40  Standard Class
180515              0             1/19/2016 1:34    Second Class
180516              0            1/20/2016 21:00  Standard Class
180517              0            1/18/2016 20:18  Standard Class
180518              0            1/19/2016 18:54  Standard Class

[180519 rows x 53 columns]>

In [6]:
data.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [3]:
cols = [ 'Days for shipping (real)','Days for shipment (scheduled)','Sales per customer','Delivery Status','Late_delivery_risk', 'Category Id',
        'Category Name', 'Customer City', 'Customer Country', 'Customer Id','order date (DateOrders)', 'Order Id','Sales','Order Region', 'Order State', 
        'Order Status','Product Name', 'Product Price','Product Status', 'shipping date (DateOrders)', 'Shipping Mode','Order Item Quantity',
        'Order Item Total', 'Order Profit Per Order' ]
#v we dont need all entire datasset we need those with which we needed

In [4]:
data = data[cols].copy()
data.isnull().sum().sum()   # No null values data is clear

0

In [7]:
data.dtypes     # here we can see the date is in integer value lets convert it to date first

Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Id                        int64
order date (DateOrders)           object
Order Id                           int64
Sales                            float64
Order Region                      object
Order State                       object
Order Status                      object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
Order Item Quantity                int64
Order Item Total                 float64
dtype: object

In [6]:
data["order date (DateOrders)"] = pd.to_datetime(data["order date (DateOrders)"])

In [5]:
data["shipping date (DateOrders)"] = pd.to_datetime(data["shipping date (DateOrders)"])

Basic Data Manupulation

In [7]:
data.columns = (data.columns
                .str.strip()
                .str.lower()
                .str.replace(" ","_")
                .str.replace(r"[()]","", regex =True ))
data.columns

Index(['days_for_shipping_real', 'days_for_shipment_scheduled',
       'sales_per_customer', 'delivery_status', 'late_delivery_risk',
       'category_id', 'category_name', 'customer_city', 'customer_country',
       'customer_id', 'order_date_dateorders', 'order_id', 'sales',
       'order_region', 'order_state', 'order_status', 'product_name',
       'product_price', 'product_status', 'shipping_date_dateorders',
       'shipping_mode', 'order_item_quantity', 'order_item_total',
       'order_profit_per_order'],
      dtype='object')

# Insights

Lead Time Variance

In [37]:
data["lead_time_variance"] = data["days_for_shipping_real"] - data["days_for_shipment_scheduled"]

conditions = [ 
    data["lead_time_variance"] == 0,
    data["lead_time_variance"] < 0             
]
choices = ["On-Time","Early"]

data["shipment_status"] = np.select( conditions, choices, default = "Late")

# to get shipment delivery status

In [38]:
data.drop(columns = ["product_status"], inplace = True)
data.drop(columns = ["delivery_status"], inplace = True)

In [39]:
data.rename(columns ={ "order_profit_per_order": "profit_per_order"}, inplace = True)
data.columns

Index(['days_for_shipping_real', 'days_for_shipment_scheduled',
       'sales_per_customer', 'late_delivery_risk', 'category_id',
       'category_name', 'customer_city', 'customer_country', 'customer_id',
       'order_date_dateorders', 'order_id', 'sales', 'order_region',
       'order_state', 'order_status', 'product_name', 'product_price',
       'shipping_date_dateorders', 'shipping_mode', 'order_item_quantity',
       'order_item_total', 'profit_per_order', 'lead_time_variance',
       'shipment_status'],
      dtype='object')

In [40]:
data.rename(columns = {"profit_per_order" : "profit"}, inplace = True)

In [41]:
data["profit_margin"] = data["profit"] / data["sales"]

Profit Margin %

In [43]:
data["profit_margin_pct"] = (data["profit"] / data["sales"]) * 100
print(f"Profit Margin is :{data['profit_margin_pct']}")

Profit Margin is :0          27.841342
1         -75.999999
2         -75.600305
3           6.974829
4          40.948896
             ...
180514     10.000500
180515   -153.450173
180516     35.279263
180517     46.559826
180518     42.239610
Name: profit_margin_pct, Length: 180519, dtype: float64

## Risk Category (condition-based) — Without ML

In [44]:
condition = [ (data["late_delivery_risk"] == 1) &(data["lead_time_variance"] > 3),
             (data["late_delivery_risk"] == 1) & (data["lead_time_variance"] > 1)]

choice = ["High","Medium"]

data["risk_category"] = np.select(condition,
                                  choice,
                                  default = "Low")
data["risk_category"]

0         Low
1         Low
2         Low
3         Low
4         Low
         ...
180514    Low
180515    Low
180516    Low
180517    Low
180518    Low
Name: risk_category, Length: 180519, dtype: object

In [45]:
data

,days_for_shipping_real,days_for_shipment_scheduled,sales_per_customer,late_delivery_risk,category_id,category_name,customer_city,customer_country,customer_id,order_date_dateorders,...,shipping_date_dateorders,shipping_mode,order_item_quantity,order_item_total,profit,lead_time_variance,shipment_status,profit_margin,profit_margin_pct,risk_category
0,3,4,314.640015,0,73,Sporting Goods,Caguas,Puerto Rico,20755,2018-01-31 22:56:00,...,2018-02-03 22:56:00,Standard Class,1,314.640015,91.250000,-1,Early,0.278413,27.841342,Low
1,5,4,311.359985,1,73,Sporting Goods,Caguas,Puerto Rico,19492,2018-01-13 12:27:00,...,2018-01-18 12:27:00,Standard Class,1,311.359985,-249.089996,1,Late,-0.760000,-75.999999,Low
2,4,4,309.720001,0,73,Sporting Goods,San Jose,EE. UU.,19491,2018-01-13 12:06:00,...,2018-01-17 12:06:00,Standard Class,1,309.720001,-247.779999,0,On-Time,-0.756003,-75.600305,Low
3,3,4,304.809998,0,73,Sporting Goods,Los Angeles,EE. UU.,19490,2018-01-13 11:45:00,...,2018-01-16 11:45:00,Standard Class,1,304.809998,22.860001,-1,Early,0.069748,6.974829,Low
4,2,4,298.250000,0,73,Sporting Goods,Caguas,Puerto Rico,19489,2018-01-13 11:24:00,...,2018-01-15 11:24:00,Standard Class,1,298.250000,134.210007,-2,Early,0.409489,40.948896,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
180514,4,4,399.980011,0,45,Fishing,Brooklyn,EE. UU.,1005,2016-01-16 03:40:00,...,2016-01-20 03:40:00,Standard Class,1,399.980011,40.000000,0,On-Time,0.100005,10.000500,Low
180515,3,2,395.980011,1,45,Fishing,Bakersfield,EE. UU.,9141,2016-01-16 01:34:00,...,2016-01-19 01:34:00,Second Class,1,395.980011,-613.770019,1,Late,-1.534502,-153.450173,Low
180516,5,4,391.980011,1,45,Fishing,Bristol,EE. UU.,291,2016-01-15 21:00:00,...,2016-01-20 21:00:00,Standard Class,1,391.980011,141.110001,1,Late,0.352793,35.279263,Low
180517,3,4,387.980011,0,45,Fishing,Caguas,Puerto Rico,2813,2016-01-15 20:18:00,...,2016-01-18 20:18:00,Standard Class,1,387.980011,186.229996,-1,Early,0.465598,46.559826,Low
180518,4,4,383.980011,0,45,Fishing,Caguas,Puerto Rico,7547,2016-01-15 18:54:00,...,2016-01-19 18:54:00,Standard Class,1,383.980011,168.949997,0,On-Time,0.422396,42.239610,Low

## Save transformed dataset into csv

In [48]:
data.to_csv("cleaned_data.csv", index = False,encoding = "utf-8-sig",quoting=1 )

In [49]:
data.columns

Index(['days_for_shipping_real', 'days_for_shipment_scheduled',
       'sales_per_customer', 'late_delivery_risk', 'category_id',
       'category_name', 'customer_city', 'customer_country', 'customer_id',
       'order_date_dateorders', 'order_id', 'sales', 'order_region',
       'order_state', 'order_status', 'product_name', 'product_price',
       'shipping_date_dateorders', 'shipping_mode', 'order_item_quantity',
       'order_item_total', 'profit', 'lead_time_variance', 'shipment_status',
       'profit_margin', 'profit_margin_pct', 'risk_category'],
      dtype='object')

In [8]:
data.sales.sum()

36784735.01337984

In [11]:
data.order_id.count()

180519